[tool.poetry]
name = "pwngen"
version = "0.1.0"
description = ""
authors = ["Miguel Angel Sanchez <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pycparser = "^2.22"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
